//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zara.Web.Views.CommerceTemplates.ProductListing {
    
    
    public partial class ZaraCatalogNodeTemplate {
        
        /// <summary>
        /// subCategories control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Zara.Web.Views.CommerceTemplates.ProductListing.Units.SubCategoriesList subCategories;
        
        /// <summary>
        /// entries control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Zara.Web.Views.CommerceTemplates.ProductListing.Units.EntriesList entries;
    }
}
